version: "1"

services:
  redis-server:
    image: redislabs/rebloom:latest
    ports:
      - 6379:6379
    container_name: redis-server

  redis-go-service:
    image: github.com/tomkaith13/redis-u-service:latest

    environment:
      - REDIS_DB_URL=redis-server:6379
      - REDIS_DB_PASSWORD=
      - REDIS_DB=0
    ports:
      - 8080:8080
    depends_on:
      - redis-server
    container_name: redis-go-service